services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/dags
    volumes:
      - ./experiments:/dags      
      - ./packages:/packages

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.1.0
    environment:
      PGADMIN_DEFAULT_EMAIL: hoi@hoi.nl
      PGADMIN_DEFAULT_PASSWORD: hoi
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
      PGADMIN_CONFIG_SERVER_MODE: "False"      
    ports:
      - 8100:80
