version: '3'

services:
  airflow:
    build:  
      context: .
      args:
        - AZURE_ARTIFACTS_TOKEN=${AZURE_ARTIFACTS_TOKEN}
    container_name: airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/database/airflow.db
      - MLFLOW_TRACKING_URI=http://mlflow:9000
      - AIRFLOW__CORE__DAGS_FOLDER=/dags-repo/airflow/experiments
    volumes:
      - dags-repo:/dags-repo      
      - ./experiments/dev:/dags-repo/airflow/experiments/_local/dev # Directly mount local folder for easy testing
      - ${STORAGE_LOCATION}/airflow/logs:/opt/airflow/logs
      - ${STORAGE_LOCATION}/airflow/database:/opt/airflow/database
    ports:
      - 8080:8080
    command: standalone
    mem_limit: ${WORKER_MEM}
    cpu_count: ${WORKER_CPU}
    depends_on: 
      - git-sync

  git-sync:
    image: registry.k8s.io/git-sync/git-sync:v4.4.0
    container_name: git-sync
    user: root
    environment:
      - GIT_SYNC_REPO=https://github.com/Pim-Mostert/airflow-mlflow.git
      - GIT_SYNC_BRANCH=main
      - GIT_SYNC_WAIT=60  # Sync interval in seconds
      - GIT_SYNC_DEPTH=1  # Shallow clone for performance
      - GIT_SYNC_ROOT=/dags-repo
      - GIT_SYNC_DEST=/dags-repo/airflow
    volumes:
      - dags-repo:/dags-repo
        
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.1
    container_name: mlflow
    volumes:
      - ${STORAGE_LOCATION}/mlflow/database:/mlflow/database
      - ${STORAGE_LOCATION}/mlflow/artifacts:/mlflow/artifacts
    ports:
      - 9000:9000
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/database/mlflow.db
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts
      --port 9000
      --host 0.0.0.0
      
volumes:
  dags-repo:
    