services:
  airflow-webserver:
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/dags/experiments
    volumes:
      - ./:/dags
  
  airflow-scheduler:
    build:
      context: .
      dockerfile: Dockerfile.airflow.dev
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/dags/experiments
      - DAGS_WORKDIR=/dags
    volumes:
      - ./:/dags
      - ./packages:/packages
