services:
  airflow:
    container_name: airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/database/airflow.db
      - MLFLOW_TRACKING_URI=http://mlflow:9000
      - AIRFLOW__WEBSERVER__AUTH_ROLE_PUBLIC=Admin
      - GIT_HASH_FILE_NAME=${GIT_HASH_FILE_NAME}
    volumes:
      - ./airflow/webserver_config.py:/opt/airflow/webserver_config.py
      - ${STORAGE_LOCATION}/airflow/logs:/opt/airflow/logs
      - ${STORAGE_LOCATION}/airflow/database:/opt/airflow/database
    ports:
      - 8080:8080
    command: standalone
    mem_limit: ${WORKER_MEM}
    cpu_count: ${WORKER_CPU}

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.1
    container_name: mlflow
    volumes:
      - ${STORAGE_LOCATION}/mlflow/database:/mlflow/database
      - ${STORAGE_LOCATION}/mlflow/artifacts:/mlflow/artifacts
    ports:
      - 9000:9000
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/database/mlflow.db
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts
      --port 9000
      --host 0.0.0.0
      