version: '3'

services:
  airflow:
    build:  
      context: .
      args:
        - AZURE_ARTIFACTS_TOKEN=${AZURE_ARTIFACTS_TOKEN}
    container_name: airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/database/airflow.db
      - MLFLOW_TRACKING_URI=http://mlflow:9000
    volumes:
      - ${DAGS_LOCATION}:/opt/airflow/dags
      - ${STORAGE_LOCATION}/airflow/logs:/opt/airflow/logs
      - ${STORAGE_LOCATION}/airflow/database:/opt/airflow/database
    ports:
      - 8080:8080
    command: standalone
    mem_limit: 6gb  
    cpu_count: 6
  
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.1
    container_name: mlflow
    volumes:
      - ${STORAGE_LOCATION}/mlflow/database:/mlflow/database
      - ${STORAGE_LOCATION}/mlflow/artifacts:/mlflow/artifacts
    ports:
      - 9000:9000
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/database/mlflow.db
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts
      --port 9000
      --host 0.0.0.0
      