x-airflow-common: &airflow-dev-common
  build:
    context: .
    dockerfile: Dockerfile.airflow.dev
  environment:
    - AIRFLOW__CORE__DAGS_FOLDER=/dags
  volumes:
    - ./experiments:/dags
    - ./packages:/packages
    
services:
  airflow-webserver:
    <<: *airflow-dev-common
  
  airflow-scheduler:
    <<: *airflow-dev-common