version: '3'

services:
  standalone:
    build: .
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/database/airflow.db
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./database:/opt/airflow/database
      - ./output:/tmp/
    ports:
      - "8080:8080"
    command: standalone
