version: '3'

services:
  airflow:
    build: .
    container_name: airflow
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/database/airflow.db
      - MLFLOW_TRACKING_URI=http://mlflow:9000
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/database:/opt/airflow/database
    ports:
      - 8080:8080
    command: standalone
  
  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.20.1
    container_name: mlflow
    volumes:
      - ./mlflow/database:/mlflow/database
      - ./mlflow/artifacts:/mlflow/artifacts
    ports:
      - 9000:9000
    command: >
      mlflow server
      --backend-store-uri sqlite:///mlflow/database/mlflow.db
      --artifacts-destination /mlflow/artifacts
      --serve-artifacts
      --port 9000
      --host 0.0.0.0

  


