services:
  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow.dev
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/dags
    volumes:
      - ./experiments:/dags      
      - ./packages:/packages
