[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dags_common"
dynamic = ["dependencies", "version"]

[tool.setuptools.dynamic]
version = {attr = "dags_common.__version__"}
dependencies = {file = ["requirements.txt"]}

[tool.distutils.bdist_wheel]
universal = false